### ISSUE TITLE
Scope and Tasks

### ISSUE THREAD

**Issue by HiagoPatrick** [HiagoPatrick/tarot-tribute-page#1]
- [x] Define the Scope and the tasks that needs to be done.
---
- [x] **User Story #1**: My tribute page should have an element with a corresponding _id="main"_, which contains all other elements.

- [ ] **User Story #2**: I should see an element with a corresponding _id="title"_, which contains a string (i.e. text) that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").

- [ ] **User Story #3**: I should see a div element with a corresponding _id="img-div"_.

- [ ] **User Story #4**: Within the img-div element, I should see an img element with a corresponding _id="image"_.

- [ ] **User Story #5**: Within the img-div element, I should see an element with a corresponding _id="img-caption"_ that contains textual content describing the image shown in img-div.

- [ ] **User Story #6**: I should see an element with a corresponding _id="tribute-info"_, which contains textual content describing the subject of the tribute page.

- [ ] **User Story #7**: I should see an a element with a corresponding _id="tribute-link"_, which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your element an attribute of target and set it to _blank in order for your link to open in a new tab (i.e. target="_blank").

- [ ] **User Story #8**: The img element should responsively resize, relative to the width of its parent element, without exceeding its original size.

- [ ] **User Story #9**: The img element should be centered within its parent element.

- [ ] Once you're done, submit the URL to your working project with all its tests passing.

---

- [ ] **HTML** 
  - [ ] Define the basic structure
  - [ ] Implement the content
  - [ ] Implement the stylesheet

- [ ] **CSS** 
  - [ ] Define the basic body structure
  - [ ] Style the divs
  - [ ] Load bootstrap
  - [ ] Do all the Retouch
